name: Cypress Tests

on:
  push:
    branches: [main]
    paths:
      - 'cypress/e2e/coffee/**'
      - 'cypress/e2e/saucedemo/**'
  workflow_dispatch:

jobs:
  cypress_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Compilar TypeScript
        run: npx tsc

      - name: Selecionar testes impactados
        run: |
          TESTS=$(node dist/scripts/select-tests.js)
          echo "TESTS=$TESTS" >> $GITHUB_ENV
          echo "Testes selecionados: $TESTS"

      - name: Rodar Testes do Cypress
        run: |
          echo "Rodando testes: $TESTS"
          npx cypress run --spec "$TESTS"

      - name: Salvar vídeos do Cypress
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
