name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests with Mochawesome
        run: |
          npx cypress run
        continue-on-error: true

      - name: Merge Mochawesome reports
        if: always()
        run: npx mochawesome-merge cypress/reports/mochawesome/*.json > cypress/reports/mochawesome/report.json

      - name: Generate HTML report
        if: always()
        run: npx marge cypress/reports/mochawesome/report.json --reportDir cypress/reports/mochawesome

      - name: Instalar K6
        run: |
          curl -L -o k6.zip https://github.com/grafana/k6/releases/download/v0.47.0/k6-v0.47.0-linux-amd64.tar.gz
          tar -xzf k6.zip
          sudo mv k6-v0.47.0-linux-amd64/k6 /usr/local/bin/

      - name: Executar testes de performance
        continue-on-error: true
        run: |
          cd k6
          k6 run --quiet saucedemo-performance.ts || echo "SauceDemo test completed with issues"
          k6 run --quiet coffee-performance.ts || echo "Coffee test completed with issues"

      - name: Upload Mochawesome report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome

      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "❌ Cypress Tests Failed"
          to: "seuemail@dominio.com"
          from: "QA Bot <${{ secrets.EMAIL_USER }}>"
          body: |
            Os testes do Cypress falharam.
            Relatório anexado.
          attachments: cypress/reports/mochawesome/report.html
