name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests with Mochawesome
        run: |
          npx cypress run --reporter mochawesome --reporter-options reportDir=cypress/reports/mochawesome,overwrite=false,html=false,json=true
        continue-on-error: true

      - name: Merge Mochawesome reports
        if: always()
        run: npx mochawesome-merge cypress/reports/mochawesome/*.json > cypress/reports/mochawesome/report.json

      - name: Generate HTML report
        if: always()
        run: npx marge cypress/reports/mochawesome/report.json --reportDir cypress/reports/mochawesome

      - name: Upload Mochawesome report as artifact
         if: always()
         uses: actions/upload-artifact@v4
         with:
         name: mochawesome-report
         path: cypress/reports/mochawesome


      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "❌ Cypress Tests Failed"
          to: "seuemail@dominio.com"
          from: "QA Bot <${{ secrets.EMAIL_USER }}>"
          body: |
            Os testes do Cypress falharam.
            Relatório anexado.
          attachments: cypress/reports/mochawesome/report.html
