name: Cypress Tests

on:
  push:
    branches: [main]
    paths:
      - 'cypress/e2e/coffee/**'
      - 'cypress/e2e/saucedemo/**'
  workflow_dispatch:

jobs:
  cypress_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalação do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Instalação das dependências
        run: npm install

      - name: Compilar TypeScript
        run: npx tsc

      - name: Selecionar testes impactados
        id: select-tests
        run: |
          SPECS=$(node dist/scripts/select-tests.js)
          echo "SPECS=$SPECS" >> $GITHUB_ENV
          echo "Specs selecionados: $SPECS"

      - name: Rodar Testes do Cypress
        run: |
          if [ -z "$SPECS" ] || [ "$SPECS" = "Nenhum teste impactado pelas alterações." ]; then
            echo "Nenhum teste específico modificado. Encerrando workflow."
          else
            echo "Rodando testes: $SPECS"
            npx cypress run --spec "$SPECS"
          fi

      - name: Salvar vídeos do Cypress
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos